### ISSUE TITLE
Bug Youtube fullscreen

### ISSUE THREAD

**Issue by Wiripse** [FLKone/HFRplus#108]
Quand on ouvre une vidéo Youtube dans le navigateur interne et qu'on la regarde en fullscreen, impossible de la réduire. 

Obligé de killer l'app pour retourner à HFR.

**Comment by FLKone** [comment]
:o:

**Comment by Wiripse** [comment]
Rejetée alors que tu as apporté un correctif ? 

Objection !!!

**Comment by FLKone** [comment]
J'ai rien corrigé :o:  ça devait être un bug dans iOS :D
