### ISSUE TITLE
Suppression d'un message

### ISSUE THREAD

**Issue by Wiripse** [FLKone/HFRplus#112]
Ajouter la possibilité de supprimer un de ses messages.

Idée : ajouter un item dans le menu qui s'affiche sur quand on clique sur "+" dans le header d'un post. En plus de "Editer", mettre "Supprimer".
Ou comme il ne reste plus beaucoup de place, mettre une icône de poubelle ?

**Comment by FLKone** [comment]
https://github.com/FLKone/HFRplus/issues/14
