### ISSUE TITLE
Emplacement du bouton favori

### ISSUE THREAD

**Issue by ViniHFR** [FLKone/HFRplus#130]
Comme je suis un flemmard et que je ne lis pas tout un topic d'un coup, je pense que cela serait plus logique d'avoir le bouton étoile favori à la place de celui de la blacklist :o À moins que certains BL plus que favorisent dans des topics ::o:

**Comment by ViniHFR** [comment]
PS : L'icone de l'étoile est en bout de ligne, comme sur le forum n'est pas recevable :o2:

**Comment by FLKone** [comment]
Merde :o 

Voir #131 plus général, et répond aussi à la problématique.
