### ISSUE TITLE
Ouvrir dans Safari

### ISSUE THREAD

**Issue by TaciteOFF** [FLKone/HFRplus#135]
Hello,

À chaque fois que je veux montrer un post à quelqu'un, je lui envoie un screenshot.
Je pense que ça serait trop d'avoir une option "ouvrir dans safari" pour chaque page de topic et pour chaque message.
À intégrer dans le menu d'actions peut être ?

Merci!

**Comment by FLKone** [comment]
Salut et désolé pour le retour tardif, ce que tu veux pouvoir faire c'est avoir l'URL d'une page/message en particulier c'est ça ? (actuellement tu peux uniquement avoir l'URL d'un topic)

**Comment by TaciteOFF** [comment]
C'est bien ça oui @FLKone :-)
