### ISSUE TITLE
Ouvrir un lien dans le nav. intégré freeze l'app

### ISSUE THREAD

**Issue by kinoute** [FLKone/HFRplus#136]
Hey,

Sur i4 (:o) IOS 7.1.2, depuis la/les dernières versions, si je choisis d'ouvrir mes liens dans le navigateur intégré, l'appli freeze dès que je clique sur un lien. Je suis obligé de la fermer et de la réouvrir, ou d'attendre très longtemps (si je switch sur une autre app ou que je fais quelque chose d'autres en attendant l'app finit par redevenir utilisable). Le lien ne s'ouvre pas par contre. Aucun problème en choisissant Safari dans les options.

**Comment by FLKone** [comment]
Il y a de gros soucis sur iOS 7 effectivement, merci pour le retour car je n'avais pu identifier personnellement aucun des problèmes avec cette version d'iOS et pourtant il y en a beaucoup :o: 

Je sais pas trop quand tout sera corrigé mais au moins j'ai un cobaye vivant sous la main maintenant :D

**Comment by FLKone** [comment]
Encore merci @kinoute 👍
