### ISSUE TITLE
Réponse vide... ou pas

### ISSUE THREAD

**Issue by Wiripse** [FLKone/HFRplus#141]
iOS 10 HFR+ 1.10.5

-Arriver sur le formulaire de réponse
-Faire un appui long pour faire apparaître le menu
-Choisir une option autre que coller (Bold, Italic, Image...) 
-Accepter la popup qui propose de coller ce qui est dans le clipboard
-On a donc du contenu dans le formulaire de réponse, mais le bouton "Envoyer" est toujours désactivé car on a rien écrit avec nos petits doigts boudinés

**Comment by FLKone** [comment]
Corrigé dans la version 1.10.6 :jap:
